<?php view::content(); ?>
<h3>formulario de registro</h3>
<?php echo form::open();?>
    <label>nombres
    <?php echo form::text('alumnos.nombres')?></label>
    <label>apellidos
    <?php echo form::text('alumnos.apellidos')?></label></label>
    <label>edad
    <?php echo form::text('alumnos.edad')?></label></label>
    <label>numero
    <?php echo form::text('alumnos.numero')?></label></label>
<?php echo form::close() ?>
