<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title><?php echo $titulo ?></title>
</head>
<body>
    <nav class='red'> 
        <ul>
          <li><?php echo html::Link("alumnos","Listado alumnos");?></li>
          <li><?php echo html::Link("alumnos/create","Registro alumnos");?></li>
          <li><?php echo html::Link("profesores","Listado profesores");?></li>
          <li><?php echo html::Link("profesores/registro","Registro profesores");?></li>        
        </ul>
    </nav> 
     <div class="container">
        <?php view::partial('fecha')?>
         <?php view::content() ?>
     </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

